import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
  HiOutlineCircleStack,
  HiOutlineCloud,
  HiOutlineCog6Tooth,
  HiOutlineCommandLine,
  HiOutlineServerStack,
  HiOutlineShieldCheck,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiAmazonwebservices,
  SiDjango,
  SiDocker,
  SiDotnet,
  SiGit,
  SiGitlab,
  SiKubernetes,
  SiLinux,
  SiPostgresql,
  SiPython,
  SiReact,
  SiSharp,
  SiTypescript,
} from "react-icons/si";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  cicd: HiOutlineCommandLine,
  cloud: HiOutlineCloud,
  database: HiOutlineCircleStack,
  infrastructure: HiOutlineServerStack,
  security: HiOutlineShieldCheck,
  tooling: HiOutlineCog6Tooth,
  aws: SiAmazonwebservices,
  csharp: SiSharp,
  django: SiDjango,
  docker: SiDocker,
  dotnet: SiDotnet,
  entityframework: HiOutlineCircleStack,
  git: SiGit,
  gitlab: SiGitlab,
  kubernetes: SiKubernetes,
  javascript: SiJavascript,
  linux: SiLinux,
  nextjs: SiNextdotjs,
  postgresql: SiPostgresql,
  python: SiPython,
  react: SiReact,
  mssql: HiOutlineCircleStack,
  supabase: SiSupabase,
  typescript: SiTypescript,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
